/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectacme.view;

import java.awt.Color;

/**
 *
 * @author Sebastian
 */
public class InterfaceAccssesVehicles extends javax.swing.JFrame {

    int xMouse, yMouse;
    public InterfaceAccssesVehicles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateButton24 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        textID = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        ExitButton = new javax.swing.JPanel();
        TextExitButton = new javax.swing.JLabel();
        ImageSudoInterface = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        textName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        TextButton = new javax.swing.JLabel();
        textName1 = new javax.swing.JLabel();
        inputName1 = new javax.swing.JTextField();
        inputName2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateButton24.setBackground(new java.awt.Color(136, 169, 195));
        CreateButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateButton24CreateButtonMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Accsses");

        javax.swing.GroupLayout CreateButton24Layout = new javax.swing.GroupLayout(CreateButton24);
        CreateButton24.setLayout(CreateButton24Layout);
        CreateButton24Layout.setHorizontalGroup(
            CreateButton24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        CreateButton24Layout.setVerticalGroup(
            CreateButton24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(CreateButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, -1));

        textID.setFont(new java.awt.Font("Rasa Light", 0, 18)); // NOI18N
        textID.setText("ID");
        getContentPane().add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        inputID.setForeground(new java.awt.Color(102, 102, 102));
        inputID.setText("enter the ID");
        inputID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputIDMousePressed(evt);
            }
        });
        inputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDActionPerformed(evt);
            }
        });
        getContentPane().add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 214, 166, 36));

        ExitButton.setBackground(new java.awt.Color(136, 169, 195));

        TextExitButton.setBackground(new java.awt.Color(136, 169, 195));
        TextExitButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TextExitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextExitButton.setText("X");
        TextExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextExitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ExitButtonLayout = new javax.swing.GroupLayout(ExitButton);
        ExitButton.setLayout(ExitButtonLayout);
        ExitButtonLayout.setHorizontalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        ExitButtonLayout.setVerticalGroup(
            ExitButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 6, -1, -1));

        ImageSudoInterface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectacme/view/images/vehicleImage.jpg"))); // NOI18N
        ImageSudoInterface.setText("jLabel1");
        getContentPane().add(ImageSudoInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 350, 560));

        Header.setBackground(new java.awt.Color(136, 169, 195));
        Header.setForeground(new java.awt.Color(136, 169, 195));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        textName.setFont(new java.awt.Font("Rasa Light", 0, 18)); // NOI18N
        textName.setText("Plate");
        getContentPane().add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        inputName.setForeground(new java.awt.Color(102, 102, 102));
        inputName.setText("enter the plate");
        inputName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputNameMousePressed(evt);
            }
        });
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        getContentPane().add(inputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 166, 36));

        Title.setFont(new java.awt.Font("MathJax_Typewriter", 0, 24)); // NOI18N
        Title.setText("Login Vehicles");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 91, 248, 37));

        TextButton.setFont(new java.awt.Font("Rasa Light", 0, 24)); // NOI18N
        TextButton.setForeground(new java.awt.Color(255, 255, 255));
        TextButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextButton.setText("Accesses");
        TextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextButtonMouseClicked(evt);
            }
        });
        getContentPane().add(TextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 411, 703, 42));

        textName1.setFont(new java.awt.Font("Rasa Light", 0, 18)); // NOI18N
        textName1.setText("Type");
        getContentPane().add(textName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 178, -1, -1));

        inputName1.setForeground(new java.awt.Color(102, 102, 102));
        inputName1.setText("enter the type");
        inputName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputName1MousePressed(evt);
            }
        });
        inputName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputName1ActionPerformed(evt);
            }
        });
        getContentPane().add(inputName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 214, 166, 36));

        inputName2.setForeground(new java.awt.Color(102, 102, 102));
        inputName2.setText("enter the Name");
        inputName2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputName2MousePressed(evt);
            }
        });
        inputName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputName2ActionPerformed(evt);
            }
        });
        getContentPane().add(inputName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 214, 166, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButton24CreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButton24CreateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateButton24CreateButtonMouseClicked

    private void inputIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputIDMousePressed
        inputID.setText("");
        inputID.setForeground(Color.black);
        inputName.setText("Enter the name");
        inputName.setForeground(Color.gray);
    }//GEN-LAST:event_inputIDMousePressed

    private void inputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDActionPerformed

    private void TextExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TextExitButtonMouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x- xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void inputNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNameMousePressed
        inputID.setText("Enter the ID");
        inputID.setForeground(Color.gray);
        inputName.setText("");
        inputName.setForeground(Color.black);
    }//GEN-LAST:event_inputNameMousePressed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void TextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextButtonMouseClicked

    }//GEN-LAST:event_TextButtonMouseClicked

    private void inputName1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputName1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputName1MousePressed

    private void inputName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputName1ActionPerformed

    private void inputName2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputName2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputName2MousePressed

    private void inputName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputName2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAccssesVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAccssesVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAccssesVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAccssesVehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAccssesVehicles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateButton24;
    private javax.swing.JPanel ExitButton;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel ImageSudoInterface;
    private javax.swing.JLabel TextButton;
    private javax.swing.JLabel TextExitButton;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputName1;
    private javax.swing.JTextField inputName2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textName1;
    // End of variables declaration//GEN-END:variables
}
